# Generated by Django 6.0.2 on 2026-02-21 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sick_days', models.IntegerField(default=20)),
                ('casual_days', models.IntegerField(default=5)),
                ('earned_days', models.IntegerField(default=10)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Leave_app.employee')),
            ],
        ),
    ]
