# Generated by Django 6.0.2 on 2026-02-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave_app', '0002_leavebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Manager', 'Manager'), ('Staff', 'Staff')], default='Staff', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='leave',
            name='manager_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
