# Generated by Django 6.0.2 on 2026-02-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave_app', '0004_employee_manager_leave_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='earned_days',
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick', 'Sick Leave'), ('Casual', 'Casual Leave')], max_length=20),
        ),
    ]
